version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - printf '[{"name":"MyService","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/default/tomcat-webserver-service:latest > imagedefinitions.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-boot-web-jsp-1.0.war
    - imagedefinitions.json
